export const html = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>iKuuu 签到</title><link rel="stylesheet" href="/app.css"></head><body><main>
<header><h1>iKuuu 签到</h1><p>每天北京时间 08:17 自动执行，失败后等待 10、30、100 分钟重试。</p></header>
<p id="message" role="status" aria-live="polite"></p>
<section id="loginPanel" hidden><h2>登录</h2><form id="loginForm"><input name="username" type="hidden" value="admin" autocomplete="username"><label for="password">登录密码</label><input id="password" type="password" autocomplete="current-password" maxlength="128" required><button type="submit">登录</button></form></section>
<section id="recoveryPanel" hidden><details id="recoveryDetails"><summary id="recoveryTitle">忘记密码？使用恢复码重置</summary><p>恢复码是部署时生成的原管理令牌。设置或重置密码后，所有已登录会话都会失效，后台签到继续运行。</p><form id="recoveryForm"><label for="recoveryCode">恢复码</label><input id="recoveryCode" type="password" autocomplete="off" maxlength="256" required><label for="recoveryPassword">新密码</label><input id="recoveryPassword" type="password" autocomplete="new-password" minlength="10" maxlength="128" required><label for="recoveryConfirm">确认新密码</label><input id="recoveryConfirm" type="password" autocomplete="new-password" minlength="10" maxlength="128" required><button type="submit">设置 / 重置密码</button></form></details></section>
<div id="dashboard" hidden>
<section><div class="heading"><h2>运行状态</h2><button id="logout">退出登录</button></div><dl id="facts"></dl><div class="actions"><button id="load">刷新状态</button><button id="run">立即检查</button><button id="pause">暂停签到</button><button id="resume">恢复签到</button></div></section>
<section><h2>更新 Cookie</h2><p>登录 iKuuu 后复制完整 Cookie。当天尚未签到时，更新后会立即恢复任务。</p><label for="cookie">Cookie</label><textarea id="cookie" rows="4" autocomplete="off" spellcheck="false" placeholder="粘贴一行完整 Cookie"></textarea><button id="update">保存并恢复签到</button></section>
<section><h2>修改登录密码</h2><p>密码须为 10–128 个字符。修改后全部会话失效，需要重新登录；后台签到继续运行。</p><form id="changeForm"><label for="currentPassword">当前密码</label><input id="currentPassword" type="password" autocomplete="current-password" maxlength="128" required><label for="newPassword">新密码</label><input id="newPassword" type="password" autocomplete="new-password" minlength="10" maxlength="128" required><label for="newConfirm">确认新密码</label><input id="newConfirm" type="password" autocomplete="new-password" minlength="10" maxlength="128" required><button type="submit">修改密码并退出所有会话</button></form></section>
<section><h2>最近记录</h2><div id="history"></div></section>
</div><footer>时间均为北京时间。Cookie 失效时停止重试，更新后恢复。通知邮件的“已提交”不代表已送达。</footer>
</main><script src="/app.js" defer></script></body></html>`;

export const css = `:root{font-family:system-ui,sans-serif;color:#182638;background:#f3f6fb}*{box-sizing:border-box}body{margin:0}main{max-width:800px;padding:32px 20px;margin:auto}header{margin-bottom:24px}h1{font-size:30px}h2{font-size:20px}p,footer{line-height:1.65;color:#536277}section{background:white;border:1px solid #dce4ef;border-radius:12px;padding:22px;margin:18px 0}label{display:block;font-weight:600;margin:12px 0 8px}input,textarea{width:100%;padding:12px;border:1px solid #b9c6d9;border-radius:6px;font:inherit}textarea{font-family:monospace}button{padding:11px 16px;background:#265bcb;color:white;border:0;border-radius:6px;cursor:pointer;margin:12px 8px 0 0}button:disabled{opacity:.5;cursor:wait}.heading{display:flex;align-items:center;justify-content:space-between}.heading button{margin:0}.hint,footer{font-size:13px}dl{display:grid;grid-template-columns:130px 1fr;gap:14px}dt{color:#536277}dd{margin:0;overflow-wrap:anywhere}.record{padding:12px 0;border-bottom:1px solid #e7edf5}.error{color:#aa2634}#message{overflow-wrap:anywhere}summary{cursor:pointer;font-weight:600}[hidden]{display:none!important}@media(max-width:480px){main{padding:16px}section{padding:16px}dl{grid-template-columns:105px 1fr}}`;

export const js = `const get=id=>document.getElementById(id);const labels={pending:'等待执行',running:'正在执行',retrying:'等待重试',success:'签到完成',failed:'重试耗尽',blocked_cookie:'Cookie 已失效',paused:'已暂停',expired:'已过期'};
let authenticated=false;const channel=typeof BroadcastChannel==='function'?new BroadcastChannel('ikuuu-auth'):null;
const time=ms=>ms?new Date(ms).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'—';
function message(text,error=false){get('message').textContent=text;get('message').className=error?'error':'';}
function clearFields(){document.querySelectorAll('input[type=password],textarea').forEach(e=>e.value='');}
function showAuth(s){authenticated=s.authenticated;get('dashboard').hidden=!authenticated;get('loginPanel').hidden=authenticated||!s.configured;get('recoveryPanel').hidden=authenticated;get('recoveryTitle').textContent=s.configured?'忘记密码？使用恢复码重置':'首次使用：设置登录密码';get('recoveryDetails').open=!s.configured;if(!authenticated){get('facts').replaceChildren();get('history').replaceChildren();clearFields();}}
function signedOut(){showAuth({configured:true,authenticated:false});channel?.postMessage('signed-out');}
if(channel)channel.onmessage=e=>{if(e.data==='signed-out'){showAuth({configured:true,authenticated:false});message('会话已退出，请重新登录');}};
function render(s){const run=s.todayRun;const schedule=s.jobs.filter(j=>j.type==='daily'||j.type==='run').sort((a,b)=>a.due-b.due)[0];const notice=s.notices.at(-1);const facts={'今天':s.today,'签到状态':s.lastSuccessDate===s.today?'签到完成':s.blocked?'等待更新 Cookie':labels[run?.status]||'尚未执行','尝试次数':run?.attempts||0,'今日领取':run?.gained||'—','剩余流量':run?.remaining||'—','当前域名':s.currentDomain,'下次签到':s.enabled&&!s.blocked?time(schedule?.due):'等待恢复','Cookie 到期标记':time(s.credential?.expiry*1000),'邮件通知':!s.mailConfigured?'尚未配置 SMTP':notice?({sent:'已提交发送',pending:'等待发送',failed:'发送失败',superseded:'已取消'}[notice.status]||notice.status):'暂无通知'};get('facts').replaceChildren();for(const[k,v]of Object.entries(facts)){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=String(v);get('facts').append(dt,dd);}get('history').replaceChildren();for(const r of s.history.slice(0,14)){const item=document.createElement('div');item.className='record';item.textContent=r.date+' · '+(labels[r.status]||r.status)+' · '+r.attempts+' 次'+(r.lastError?' · '+r.lastError:'');get('history').append(item);}}
async function api(path,body){const response=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const result=await response.json();if(!response.ok){if(response.status===401 && authenticated)signedOut();throw Error(result.error||'请求失败');}return result;}
async function load(){const s=await api('status');render(s);return s;}
async function act(action){document.querySelectorAll('button').forEach(b=>b.disabled=true);try{const result=await action();message(result?.message||'状态已更新');}catch(e){message(e.message,true);}finally{document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function passwordPair(first,confirm){if(get(first).value!==get(confirm).value)throw Error('两次输入的密码不一致');return get(first).value;}
get('loginForm').onsubmit=e=>{e.preventDefault();act(async()=>{const result=await api('auth/login',{password:get('password').value});clearFields();showAuth(await api('auth/status'));await load();return result;});};
get('recoveryForm').onsubmit=e=>{e.preventDefault();act(async()=>{const result=await api('auth/recover',{recoveryCode:get('recoveryCode').value,password:passwordPair('recoveryPassword','recoveryConfirm')});signedOut();return result;});};
get('changeForm').onsubmit=e=>{e.preventDefault();act(async()=>{const result=await api('auth/change-password',{currentPassword:get('currentPassword').value,newPassword:passwordPair('newPassword','newConfirm')});signedOut();return result;});};
get('logout').onclick=()=>act(async()=>{const result=await api('auth/logout',{});signedOut();return result;});
get('load').onclick=()=>act(load);for(const action of ['run','pause','resume'])get(action).onclick=()=>act(async()=>{const result=await api(action,{});render(result);return result;});
get('update').onclick=()=>act(async()=>{const result=await api('cookie',{cookie:get('cookie').value});get('cookie').value='';render(result);return result;});
act(async()=>{const s=await api('auth/status');showAuth(s);if(s.authenticated)await load();return {message:s.authenticated?'已恢复登录会话':s.configured?'请输入密码登录':'请用恢复码设置首次登录密码'};});
setInterval(()=>{if(authenticated && !document.hidden)load().catch(e=>message(e.message,true));},20000);`;
